name: CI pipeline

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: sudo apt-get install imagemagick lftp
      - name: Compress images
        run: |
          find src/assets/referenzen/ -name '*' -exec mogrify -resize 528x528 -quality 95\> {} \;
          find src/assets/stefan-niedermann.jpg -exec mogrify -resize 331x331 -quality 95\> {} \;
      - name: Pull .well-known
        continue-on-error: true
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror .well-known src; quit;" ${{ secrets.FTP_URL }}
      - name: Deploy new bundle
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror src . --reverse --delete --use-cache --verbose --allow-suid --no-umask --parallel=10; quit;" ${{ secrets.FTP_URL }}
